[package]
name = "Voyager-3-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
actix-web = "4.0.1" 
actix-files = "0.6.0"
log = "0.4.17"
env_logger = "0.9.0"
